

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 
    jobs:
      - job: installNodeJs
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.19.3'
          displayName: 'Install Node.js'
  - stage:
    jobs:
      - job: NPMInstall
        steps:
        - checkout: none
        - script: |
            echo Hi
          displayName: 'npm install'
  - stage:
    jobs:
      - job: checkLinting
        steps:         
        - script: |
            echo hello
          displayName: 'Check Linting'
  - stage:
    jobs:
      - job: Build
        steps:
        - script: |
            echo how r u
          displayName: 'Build'
  - stage:
    jobs:
      - job: secretKeys
        steps:
        - script: |
            echo am fine
          displayName: Output Value of Secret Keys
          # env:
          #   CLIENT_ID: $(client_ID)
        - script: |
            #sfcc-ci client:auth $env:CLIENT_ID $env:CLIENT_SECRET
            echo awesome
          displayName: 'Deploy'


          # env:
          #   CLIENT_ID: $(client_ID)
          #   CLIENT_SECRET: $(client_SECRET)
